// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJFsz2VebraG0d-aHINx5DdRGtLlFHHi8',
    appId: '1:820513932811:web:1dd9408c5f3caf2e74290e',
    messagingSenderId: '820513932811',
    projectId: 'elderly-firestore',
    authDomain: 'elderly-firestore.firebaseapp.com',
    storageBucket: 'elderly-firestore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs44aKc7A0mPbrnkcUYuEmXY-T6tuUh8o',
    appId: '1:820513932811:android:0696b2381609321e74290e',
    messagingSenderId: '820513932811',
    projectId: 'elderly-firestore',
    storageBucket: 'elderly-firestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi2Hi3Af9yYRKynETPko6EXwcaQh9dkvc',
    appId: '1:820513932811:ios:f59bdb9c2d2d9b4b74290e',
    messagingSenderId: '820513932811',
    projectId: 'elderly-firestore',
    storageBucket: 'elderly-firestore.firebasestorage.app',
    iosBundleId: 'com.example.elderlyHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi2Hi3Af9yYRKynETPko6EXwcaQh9dkvc',
    appId: '1:820513932811:ios:f59bdb9c2d2d9b4b74290e',
    messagingSenderId: '820513932811',
    projectId: 'elderly-firestore',
    storageBucket: 'elderly-firestore.firebasestorage.app',
    iosBundleId: 'com.example.elderlyHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJFsz2VebraG0d-aHINx5DdRGtLlFHHi8',
    appId: '1:820513932811:web:e6f68856f15f635974290e',
    messagingSenderId: '820513932811',
    projectId: 'elderly-firestore',
    authDomain: 'elderly-firestore.firebaseapp.com',
    storageBucket: 'elderly-firestore.firebasestorage.app',
  );
}
